### ISSUE TITLE
Some Modifications as Horns and some Sideskirts have no LocalizedNames

### ISSUE THREAD

**Issue by LiquidzDEV** [Micky5991/VehicleInfoLoader#1]
Hello,

first off nice work what you have done here!

I have seen that some Horns and other Mods have no LocalizedName under the German file.
(Horns on every Vehicle and some Mods from Buccaneer2 and other Vehicles)

**Comment by Micky5991** [comment]
First, this repo is only for the tool which parses the files of https://github.com/Micky5991/GT-MP-vehicleInfo. 

As I listed in the [known issues](https://github.com/Micky5991/GT-MP-vehicleInfo#known-issues) there are many information missing, but it is a hard to research all strings about all mods. Mostly the given data from GTA V files are used.

You have to keep in mind, that often things, which are not available for the "normal" user in the main game, that they don't have strings at all. But maybe I will create a placeholder for those names, so they are at least not empty, or when you know the language-keys for various things, just try to add them yourself or send them to GT-MP-vehicleInfo
