### ISSUE TITLE
Error at check if mod is available

### ISSUE THREAD

**Issue by raelianer** [Micky5991/VehicleInfoLoader#2]
https://github.com/Micky5991/VehicleInfoLoader/blob/ea86b5edb4b1b1bc10d55922f074276e2b912427/Data/VehicleManifest.cs#L62-L66
An error is thrown when trying to use a mod which does not exist for a given type.
For example type 11 (engine) with mod 4 on an Exemplar (hash: -5153954).

> 04:59:07.185 | Error | ScriptingEngine | EXCEPTION IN RESOURCE mygamemode INSIDE SCRIPTENGINE VehicleModder System.Reflection.TargetInvocationException: Ein Aufrufziel hat einen Ausnahmefehler verursacht. ---> System.Collections.Generic.KeyNotFoundException: Der angegebene Schlssel war nicht im W”rterbuch angegeben.
   bei System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   bei VehicleInfoLoader.Data.VehicleManifest.Mod(Int32 type, Int32 mod)
   bei MyGamemode.VehicleModder.modvehicle(Client sender, Int32 modtype, Int32 mod)
   --- Ende der internen Ausnahmestapelberwachung ---
   bei System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   bei System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   bei System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   bei GrandTheftMultiplayer.Server.Models.ScriptingEngine.<>c__DisplayClass22_0.<InvokeVoidMethod>b__0()
   bei GrandTheftMultiplayer.Server.Models.ScriptingEngine.MainThreadLoop()

I was using this code from the examples:

```
public class VehicleModder : Script {
	[Command]
	public void modvehicle(Client sender, int modtype, int mod) {
		if (!sender.isInVehicle) [
			sender.sendChatMessage("~r~You have to be in the vehicle you want to mod!");
			return;
		}
		Vehicle veh = sender.vehicle;
		VehicleManifest manifest = veh.Manifest();
		if(!manifest.HasMod(modtype, mod)) {
			sender.sendChatMessage("~r~The requested mod is not available!");
			return;
		}
		API.setVehicleMod(veh, modtype, mod);	
		sender.sendChatMessage("You modded the " + manifest.localizedName + " with: " + manifest.Mod(modtype, mod).localizedName);
	}
}
```

However, this check seems to work for me:

```
            VehicleModType vehmod = manifest.ModType(modtype);
            Dictionary<int, VehicleMod> mods = vehmod.Mods();
            if (!mods.ContainsKey(mod))
```

This seems to work as intended, but I guess it needs some overhaul:

```
        [Command]
        public void modvehicle(Client sender, int modtype, int mod)
        {
            if (!sender.isInVehicle)
            {
                sender.sendChatMessage("~r~You have to be in the vehicle you want to mod!");
                return;
            }
            Vehicle veh = sender.vehicle;
            VehicleManifest manifest = veh.Manifest();

            if (!manifest.HasMod(modtype))
            {
                sender.sendChatMessage("~r~The requested modtype is not available!");
                return;
            }

            VehicleModType vehmod = manifest.ModType(modtype);
            Dictionary<int, VehicleMod> mods = vehmod.Mods();
            if (!mods.ContainsKey(mod))
            {
                sender.sendChatMessage("~r~The requested mod is not available!");
                return;
            }

            API.setVehicleMod(veh, modtype, mod);
            sender.sendChatMessage("You modded the " + manifest.localizedName + " with: " + manifest.Mod(modtype, mod).localizedName);
        }
```

**Comment by Micky5991** [comment]
Thanks for the report, the issue should be fixed now. 
The nuget package will be updated later this day.
