### ISSUE TITLE
HasMod() does not return the standard mod (-1)

### ISSUE THREAD

**Issue by raelianer** [Micky5991/VehicleInfoLoader#5]
https://github.com/Micky5991/VehicleInfoLoader/blob/3007790a8ddd94154ad2b5959edc51808041a69a/Data/VehicleManifest.cs#L59

Using this to check if the mod is available prevents setting the mod back to standard.

**Comment by Micky5991** [comment]
Not every mod type has the stock value of -1. I'll update the GT-MP-vehicleinfo for an improved version of the collected data. In general, if you want to set the mod to the default value back, just use [API.removeVehicleMod](https://wiki.gt-mp.net/index.php/RemoveVehicleMod)
